const ACTIONS ={
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',

    GET_ITEMS: 'GET_ITEMS',
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM : 'DELETE_ITEM',
    UPDATE_ITEM : 'UPDATE_ITEM',
    ITEMS_LOADING : 'ITEMS_LOADING',
    CART_LOADING : 'CART_LOADING',
    GET_CART : 'GET_CART',
    ADD_TO_CART : 'ADD_TO_CART',
    DELETE_FROM_CART : 'DELETE_FROM_CART',
    ORDERS_LOADING : 'ORDERS_LOADING',
    GET_ORDERS : 'GET_ORDERS',
    CHECKOUT : 'CHECKOUT',
    GET_ERRORS : 'GET_ERRORS',
    CLEAR_ERRORS : 'CLEAR_ERRORS',
    CLEAR_CART : 'CLEAR_CART'
}

export default ACTIONS